import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import App from './App';
import { ThemeProvider } from './hooks/useTheme';
import { AuthProvider } from './services/authService';
import RootErrorBoundary from './components/RootErrorBoundary';
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsx(RootErrorBoundary, { children: _jsx(ThemeProvider, { children: _jsx(AuthProvider, { children: _jsx(BrowserRouter, { children: _jsx(App, {}) }) }) }) }) }));
